config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: 'items#index'
  get "/items", to: "items#index", as: "items"
  post "/items", to: "items#create"
  get "/items/new", to: "items#new", as: "new_item"
  get "/items/:id", to: "items#show", as: "item"
  get "/users/:id", to: "users#show", as: "user"
  put "/items/:id", to: "items#update"
  patch "/items/:id", to: "items#update"
  delete "/items/:id", to: "items#destroy", as: "destroy_item"
  get "/items/:id/edit", to: "items#edit", as: "edit_item"

  get "/payments/success", to: "payments#success"

  get "/admins/dash", to: "admins#index", as: "admin_index"

  get "/cart", to: "carts#show", as: "cart"
  post "/cart/:id", to: "carts#create", as: "add_to_cart"
  delete "/cart/:id", to: "carts#destroy", as: "destroy_cart_item"
end

app/views/partials/_card.html.erb
  <div class="card mb-3 mx-auto">
    <div class="row g-0">
      <div class="card-img-container col-md-4">
        <%= image_tag(item.picture, alt: "image", class: "card-img") if item.picture.attached? %>
      </div>
      <div class="col-md-8">
        <div class="card-info">
          <%= link_to "#{item.title}", item_path(item), class: "neonTextTitle" %>
          <p class="card-text neonText"><%= number_to_currency(item.price, unit: "¥") %></p>
          <p class="card-text neonText">Material: <%= item.material %></p>
          <p class="card-text neonText">Limb: <%= item.limb.name %></p>
          <p class="card-text neonText">Type: <%= item.control_type %></p>
        </div>
      </div>
    </div>
  </div>

app/views/partials/_card_cart_item.html.erb
<li class="card list-group-item">
  <div class="user-item-container ms-2 me-auto">
    <%= link_to "#{item.title}", item_path(item), class: "neonText" %>
    <p class="neonText"><%= item.limb.name + "," + item.material + "," + item.control_type %></p>
    <p class="neonText"><%= number_to_currency(item.price, unit: "¥") %></p>
  </div>
  <%= link_to "Remove", destroy_cart_item_path(item.id), :method => :delete, class: "btn neonText" %>
</li>

app/views/partials/_form.html.erb
<div class="form-group form-inputs">
  <%= form_with model: @item do |form| %>
    <%= form.label :title, class: "neonText" %>
    <%= form.text_field :title, class: "form-control" %>
    <br>
    <%= form.label :description, class: "neonText" %>
    <%= form.text_area :description, class: "form-control" %>
    <br>
    <%= form.label :limb_id, class: "neonText" %>
    <%= form.select :limb_id, limbs.map {|l| [l.name, l.id]}, class: "form-control" %>
    <br>
    <%= form.label :material, class: "neonText" %>
    <%= form.select :material, ["Titanium", "Chromium", "Steel Alloy", "Carbon Fibre"], class: "form-control" %>
    <br>
    <%= form.label :control_type, class: "neonText" %>
    <%= form.select :control_type, ["Exo", "Myco", "Neural"], class: "form-control" %>
    <br>
    <%= form.label :quantity, class: "neonText" %>
    <%= form.number_field :quantity, min:1, class: "form-control" %>
    <br>
    <%= form.label :price, class: "neonText" %>
    <%= form.number_field :price, min:0, class: "form-control" %>
    <br>
    <%= form.label :picture, class: "neonText" %>
    <%= form.file_field :picture, accept: "image/png, image/jpg, image/jpeg" %>
    <br>
    <br>
    <%= form.submit %>
  <% end %>
</div>



<%# <%= simple_form_for @item do |f| %>
  <%# <%= f.input :title, placeholder: 'e.g. Bionic Arm x34 v2.0', error: 'Title is required' %>
  <%# <%= f.input :limb_id, collection: @limbs, error: 'Limb is required' %>
  <%# <%= f.input :material_id, collection: @materials,  error: 'Limb is required' %>
  <%# <%= f.input :type_id, collection: @types, error: 'Type is required' %>
  <%# <%= f.input :price, as: :integer, min: 0 %>
  <%# <%= f.input :description, as: :text, placeholder: 'e.g. Bionic Arm featuring latest enhancements', error: 'Description is required' %>
  <%# <%= f.input :image, as: :file %>
  <%# <%= f.button :submit %>
<%# <% end %>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark">
  <div class="container">
    <%= link_to "ProsMa", root_path, class: "navbar-brand", id: "navBrand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <p class="nav-link mb-0 neonText" id="navLinkName">Welcome, <%= current_user.first_name + " " + current_user.last_name %></p>
          </li>
        <% end %>  
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link neonText", id: "navLink" %>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
            <%= link_to "Add item", new_item_path, class: "nav-link neonText", id: "navLink" %>
        </li>
        <li class="nav-item">
            <%= link_to "Cart", cart_path, class: "nav-link neonText", id: "navLink" %>
        </li>
        <li class="nav-item">
            <%= link_to "View Profile", user_path(current_user.id), class: "nav-link neonText", id: "navLink" %>
        </li>
        <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link neonText", id: "navLink" %>
        </li>
          <% else %>
        <li class="nav-item">
            <%= link_to "Log in", new_user_session_path, class: "nav-link neonText", id: "navLink" %>
        </li>
        <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link neonText", id: "navLink" %>
        </li>
        <% end %>
        <% if user_signed_in? && current_user.role == "admin" %>
        <li class="nav-item">
            <%= link_to "Admin Dashboard", admin_index_path, class: "nav-link neonText", id: "navLink" %>
        </li>
        <% end %>
          <%# <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Limb Category</a>
            <ul class="dropdown-menu">
              <li>
                  <%= link_to "Arm", items_path, scope: :search, local: true class: "nav-link neonText", id: "navLink" %>
              <%# </li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li> %>
      </ul>
    </div>
  </div>
</nav>

app/views/partials/_user_item.html.erb
  <li class="card list-group-item">
    <div class="user-item-container ms-2 me-auto">
      <%= link_to "#{item.title}", item_path(item), class: "neonText" %>
      <p class="neonText"><%= item.limb.name + "," + item.material + "," + item.control_type %></p>
      <p class="neonText"><%= number_to_currency(item.price, unit: "¥") %></p>
      <p class="neonText">QTY: <%= item.quantity %></p>
    </div>
  </li>

app/views/partials/_user_list_item.html.erb
  <li class="list-group-item">
    <div class="user-container">
      <p><%= user.id %></p>
      <p>
        <%= link_to user.first_name + " " + user.last_name, user_path(user.id) %>
      </p>
      <p><%= user.email %></p>
      <p><%= user.role %></p>
      <p><%= user.created_at %></p>
    </div>
  </li>