config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: 'items#index'
  get "/items", to: "items#index", as: "items"
  post "/items", to: "items#create"
  get "/items/new", to: "items#new", as: "new_item"
  get "/items/:id", to: "items#show", as: "item"
  get "/users/:id", to: "users#show", as: "user"
  put "/items/:id", to: "items#update"
  patch "/items/:id", to: "items#update"
  delete "/items/:id", to: "items#destroy", as: "destroy_item"
  get "/items/:id/edit", to: "items#edit", as: "edit_item"

  get "/payments/success", to: "payments#success"

  get "/admins/dash", to: "admins#index", as: "admin_index"

  get "/cart", to: "carts#show", as: "cart"
  post "/cart/:id", to: "carts#create", as: "add_to_cart"
  delete "/cart/:id", to: "carts#destroy", as: "destroy_cart_item"
end

app/models/item.rb
class Item < ApplicationRecord
  #Item active record associations
  belongs_to :user
  has_one_attached :picture
  belongs_to :limb
  has_many :cart_items
  has_many :carts, through: :cart_items

  #Scopes for search and filter queries
  scope :search_by_title, -> (title) { where("title ILIKE ?", "%#{title}%")}
  scope :filter_by_limb, -> (id) {where(limb_id: id)}

  #Search method with chained scopes to return a filtered or searched items variable
  def self.search(search_hash)
    if search_hash
      Item.search_by_title(search_hash["title"]).filter_by_limb(search_hash["limb_id"])
    else
      Item.all
    end
  end

  #Validation for Items
  validates_presence_of :title, :control_type, :material, :user_id, :limb_id
  validates :description, length: { maximum: 200, exceeded_char_limit: "200 character limit"}
  validates :price, presence: true, numericality: { only_integer: true }
  validates :quantity, presence: true, numericality: { only_integer: true }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  #Actions executed before other methods in controller
  before_action :read_users, :read_limbs
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authorize_seller, only: [:new, :create]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  #New method for item instansiation
  def new
    @item = Item.new
  end

  #Create method for an item with an authentication check
  def create
    if user_signed_in?
      @item = current_user.items.create(item_params)
      redirect_to items_path
      flash[:alert] = "Item Created!"
    else
      redirect_to new_user_session_path
      flash[:alert] = "Sign in to continue"
    end
  end

  #Show method including Stripe parameters used for payments
  def show
    if current_user
      session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        customer_email: current_user.email,
        line_items: [{
          name: @item.title,
          description: @item.description,
          images: [@item.picture],
          amount: @item.price,
          currency: 'jpy',
          quantity: 1
        }],
        payment_intent_data: {
          metadata: {
            item_id: @item.id
          }
        },
        success_url: "#{root_url}payments/success?itemId=#{@item.id}",
        cancel_url: "#{root_url}items"
      )
      @session_id = session.id
    end
  end

  #Index method for item, assigning searched and filtered items to an instance variable
  def index
    @items = Item.search(params[:search]).includes(:limb, :user)
  end

  #Edit method for item
  def edit
  end

  #Update method for item
  def update
    @item.update(item_params)
    redirect_to items_path
  end

  #Destroy method enabling deletion of item
  def destroy
    @item.destroy
    flash[:alert] = "Item Deleted"
    redirect_to items_path
  end

  private 

  #Authorize seller method to check if user id is the same as item id OR admin
  def authorize_user
    unless (current_user.id == @item.user_id) || current_user.admin?
      flash[:alert] = "You are not authorized!"
      redirect_to items_path
    end
  end

  #Authorize seller method to check if user is seller or admin
  def authorize_seller
    unless current_user.seller? || current_user.admin?
      flash[:alert] = "You are not authorized!"
      redirect_to items_path
    end
  end

  #Sets item to instance variable for use, from parameters
  def set_item
    id = params[:id]
    @item = Item.find(id)
  end

  #Sets all limbs to instance variable for use
  def read_limbs
    @limbs = Limb.all
  end

  #Sets all users to instance variable for use
  def read_users
    @users = User.all
  end

  #Whitelist parameters for item instansiation
  def item_params
    params.require(:item).permit(:title, :description, :price, :material, :limb_id, :control_type, :picture)
  end
end

app/helpers/item_helper.rb
module ItemHelper
end

app/views/items/edit.html.erb
<h2 class="neonTextTitle">Edit Item</h2>

<%# Edit item form using simpleform gem %>
<%= render partial: "partials/form", locals: {item: @item, limbs: @limbs} %>

app/views/items/index.html.erb
<div class="p-4 rounded-3 m-3 position-relative form-group">
      <%= form_with(method:"get", url: items_path, scope: :search, local: true) do |form| %>
            <%= form.text_field :title, class: "form-control", :placeholder => 'Search by name' %>
            <%= form.label "Filter by Limb:", class: "neonText" %>
            <%= form.select :limb_id, @limbs.map {|l| [l.name, l.id]}, class: "form-control"  %>
            <%= form.submit "search", class: "btn neonText" %>
      <% end %>
      <div class="mt-4">
            <% @items.each do |item| %>
                  <%= render partial: "partials/card", locals: {item: item} %>
            <% end %>
      </div>
</div>

app/views/items/new.html.erb
<h2 class="neonTextTitle">Add New Item</h2>

<%= render partial: "partials/form", locals: {item: @item, limbs: @limbs} %>



app/views/items/show.html.erb
  <div class="card-body">
    <%= image_tag(@item.picture, alt: "image", class: "item-img") if @item.picture.attached? %>
    <div class="item-info">
      <h5 class="card-title neonTextTitle"><%= @item.title %></h5>
      <p class="card-text neonText"><%= @item.description %></p>
      <p class="card-text neonText price"><%= number_to_currency(@item.price, unit: "¥")  %></p>
      <p class="card-text neonText">Material: <%= @item.material %></p>
      <p class="card-text neonText">Limb: <%= @item.limb.name %></p>
      <p class="card-text neonText">Type: <%= @item.control_type %></p>
      <p class="card-text neonText">Seller: <%= @item.user.first_name + " " + @item.user.last_name %></p>
      <%= link_to "Back", items_path, class: "btn neonText" %>
      <% if current_user && (current_user.id == @item.user_id || current_user.admin?) %>
        <%= link_to "Edit", edit_item_path(@item.id), class: "btn neonText" %>
        <%= link_to "Delete", destroy_item_path(@item.id), :method => :delete, class: "btn neonText" %>
      <% end %>
      <% if current_user %>
        <button data-stripe="payment" class="btn neonText">Buy now</button>
        <%= link_to "Add to Cart", add_to_cart_path(@item), :method => :post, :class => "btn neonText" %>
      <% end %>
    </div>

  </div>
  
  <script src="https://js.stripe.com/v3/"></script>
  <script>
    document.querySelector("[data-stripe='payment']").addEventListener("click", () => {
      const stripe = Stripe("<%= Rails.application.credentials.dig(:stripe, :public_key) %>");
      stripe.redirectToCheckout({
        sessionId: "<%= @session_id %>"
      });
    });
  </script>